# Generated by Django 4.2.2 on 2023-06-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
