# Generated by Django 4.2.2 on 2023-06-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_song_delete_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Entry',
        ),
    ]
