# Generated by Django 4.2.2 on 2023-06-28 05:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_song_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_system', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Jury', 'Jury'), ('Televote', 'Tele'), ('Combined', 'Combined')], default='Combined'), size=None)),
                ('ranking', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.performance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Semi-Final 1', 'Semi 1'), ('Semi-Final 2', 'Semi 2'), ('Grand Final', 'Final')], default='Grand Final')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.entry'),
        ),
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.show'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edition'),
        ),
    ]
