# Generated by Django 4.2.2 on 2023-06-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_country_edition_performance_alter_entry_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='show',
        ),
        migrations.AddField(
            model_name='performance',
            name='show_type',
            field=models.CharField(choices=[('Semi-Final 1', 'Semi 1'), ('Semi-Final 2', 'Semi 2'), ('Grand Final', 'Final')], default='Grand Final'),
        ),
        migrations.AddField(
            model_name='performance',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.edition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
