# Generated by Django 4.2.2 on 2023-06-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_performance_show_performance_show_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='year',
        ),
    ]
