# Generated by Django 4.2.2 on 2023-06-29 18:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_performance_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='show_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting_system',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('Jury', 'Jury'), ('Televote', 'Tele'), ('Combined', 'Combined')], default='Combined'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.CharField(choices=[('Semi-Final 1', 'Semi 1'), ('Semi-Final 2', 'Semi 2'), ('Grand Final', 'Final')], default='Grand Final')),
                ('voting_system', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Jury', 'Jury'), ('Televote', 'Tele'), ('Combined', 'Combined')], default='Combined'), size=None)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.show'),
            preserve_default=False,
        ),
    ]
