# Generated by Django 4.2.2 on 2023-06-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_performance_show_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='entry',
        ),
        migrations.AddField(
            model_name='performance',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.country'),
            preserve_default=False,
        ),
    ]
