# Generated by Django 4.2.2 on 2023-06-29 22:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_performance_entry_performance_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.CharField(choices=[(1, 'Semifinal 1'), (2, 'Semifinal 2'), (3, 'Grand Final')], default=3),
        ),
        migrations.AlterField(
            model_name='show',
            name='voting_system',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Jury'), (2, 'Televote'), (3, 'Combined')], default=3), size=None),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Jury'), (2, 'Televote'), (3, 'Combined')], default=3),
        ),
    ]
