# Generated by Django 4.2.2 on 2023-07-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_result_jury_place_result_televote_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='demonym',
            field=models.CharField(default='W', max_length=50),
            preserve_default=False,
        ),
    ]
