# Generated by Django 4.2.2 on 2023-07-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_country_demonym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='demonym',
            new_name='adjective',
        ),
    ]
