# Generated by Django 4.2.2 on 2023-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_language_entry_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('countries', models.ManyToManyField(to='data.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
